/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/backtest.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Equity curves, trades and statistics */
        get: operations["backtest_api_backtest_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/costs.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statistics at every trading cost from 0 to 25 bps */
        get: operations["costs_api_costs_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decisions/{year}.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** strategy() output for each day of a year */
        get: operations["decisions_api_decisions__year__json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Regime and both signals for every backtest day */
        get: operations["history_api_history_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every live run, newest first */
        get: operations["run_list_api_runs_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{day}.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One live run with its step trace and orders */
        get: operations["run_api_runs__day__json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health, latest run and current regime */
        get: operations["status_api_status_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sweep.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backtests with nearby parameter settings */
        get: operations["sweep_api_sweep_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Build, data, test and endpoint facts */
        get: operations["system_api_system_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Account */
        Account: {
            /** Cash */
            cash: number;
            /** Equity */
            equity: number;
        };
        /** ApiCall */
        ApiCall: {
            /** At */
            at: string;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Method */
            method: string;
            /** Path */
            path: string;
            /** Status */
            status: number;
        };
        /** Backtest */
        Backtest: {
            /** Benchmark */
            benchmark: number[];
            /** Bond Lookback */
            bond_lookback: number;
            /** Cost Bps */
            cost_bps: number;
            /** Cost Drag */
            cost_drag: number;
            /** Dates */
            dates: string[];
            /** Equity */
            equity: number[];
            /** Holdout Start */
            holdout_start: string;
            /** Long Bond Lookback */
            long_bond_lookback: number;
            /** Rebalance Threshold */
            rebalance_threshold: number;
            /** Rising Rates Rsi Window */
            rising_rates_rsi_window: number;
            /** Risk On Rsi Window */
            risk_on_rsi_window: number;
            /** Run Id */
            run_id: string;
            /** Seconds */
            seconds: number;
            spy: components["schemas"]["Periods"];
            strategy: components["schemas"]["Periods"];
            /** Trades */
            trades: components["schemas"]["TradeDay"][];
            /** Trades Per Year */
            trades_per_year: number;
        };
        /** Checks */
        Checks: {
            /** Coverage */
            coverage: number | null;
            /** Failed */
            failed: number;
            /** Passed */
            passed: number;
        };
        /** CostPoint */
        CostPoint: {
            /** Cost Bps */
            cost_bps: number;
            /** Cost Drag */
            cost_drag: number;
            periods: components["schemas"]["Periods"];
        };
        /** Costs */
        Costs: {
            /** Baseline Cost Bps */
            baseline_cost_bps: number;
            /** Points */
            points: components["schemas"]["CostPoint"][];
        };
        /** Decision */
        Decision: {
            /** Checks */
            checks: components["schemas"]["RuleCheck"][];
            /** Date */
            date: string;
            /** Regime */
            regime: string;
            /** Rsi */
            rsi: {
                [key: string]: number;
            };
            /** Weights */
            weights: {
                [key: string]: number;
            };
        };
        /** Endpoint */
        Endpoint: {
            /** Files */
            files: number;
            /** Path */
            path: string;
            /** Summary */
            summary: string;
        };
        /** Fund */
        Fund: {
            /** Role */
            role: string;
            /** Ticker */
            ticker: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * History
         * @description One entry per backtest day: the regime chosen and the two signals behind it.
         */
        History: {
            /** Bond Lookback */
            bond_lookback: number;
            /** Dates */
            dates: string[];
            /** Holdout Start */
            holdout_start: string;
            /** Long Bond Lookback */
            long_bond_lookback: number;
            /** Regime */
            regime: string[];
            /** Signal 1 */
            signal_1: number[];
            /** Signal 2 */
            signal_2: number[];
        };
        /** OrderRecord */
        OrderRecord: {
            /** Client Order Id */
            client_order_id: string;
            /** Filled Avg Price */
            filled_avg_price?: number | null;
            /** Filled Qty */
            filled_qty?: number | null;
            /** Order Id */
            order_id?: string | null;
            /** Qty */
            qty: number;
            /** Side */
            side: string;
            /** Status */
            status: string;
            /** Symbol */
            symbol: string;
        };
        /** Periods */
        Periods: {
            before_holdout: components["schemas"]["Stats"];
            full: components["schemas"]["Stats"];
            holdout: components["schemas"]["Stats"];
        };
        /** Position */
        Position: {
            /** Market Value */
            market_value: number;
            /** Qty */
            qty: number;
        };
        /** RuleCheck */
        RuleCheck: {
            /** Gap */
            gap: number;
            /** Left */
            left: string;
            /** Left Return */
            left_return: number;
            /** Lookback */
            lookback: number;
            /** Passed */
            passed: boolean;
            /** Right */
            right: string;
            /** Right Return */
            right_return: number;
            /** Rule */
            rule: number;
        };
        /** Run */
        Run: {
            account: components["schemas"]["Account"] | null;
            /** Api Calls */
            api_calls: components["schemas"]["ApiCall"][];
            decision: components["schemas"]["Decision"] | null;
            /** Dry Run */
            dry_run: boolean;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Orders */
            orders: components["schemas"]["OrderRecord"][];
            /** Positions */
            positions: {
                [key: string]: components["schemas"]["Position"];
            };
            /** Started At */
            started_at: string;
            /** Status */
            status: string;
            /** Steps */
            steps: components["schemas"]["Step"][];
            /** Trading Day */
            trading_day: string;
        };
        /** RunCounts */
        RunCounts: {
            /** Failed */
            failed: number;
            /** Ok */
            ok: number;
            /** Skipped */
            skipped: number;
            /** Total */
            total: number;
        };
        /** RunSummary */
        RunSummary: {
            /** Dry Run */
            dry_run: boolean;
            /** Duration Ms */
            duration_ms: number | null;
            /** Error */
            error: string | null;
            /** Orders */
            orders: number;
            /** Regime */
            regime: string | null;
            /** Started At */
            started_at: string;
            /** Status */
            status: string;
            /** Trading Day */
            trading_day: string;
        };
        /** Schedule */
        Schedule: {
            /** Cron */
            cron: string;
            /** Timezone */
            timezone: string;
        };
        /** Stats */
        Stats: {
            /** Cagr */
            cagr: number;
            /** Max Drawdown */
            max_drawdown: number;
            /** Sharpe */
            sharpe: number;
            /** Volatility */
            volatility: number;
            /** Years */
            years: number;
        };
        /** Status */
        Status: {
            account: components["schemas"]["Account"] | null;
            /** Built At */
            built_at: string;
            /** Commit */
            commit: string | null;
            /** Data End */
            data_end: string;
            first_account: components["schemas"]["Account"] | null;
            latest_run: components["schemas"]["RunSummary"] | null;
            /** Regime */
            regime: string;
            /** Regime Date */
            regime_date: string;
            runs: components["schemas"]["RunCounts"];
            schedule: components["schemas"]["Schedule"];
            /** Weights */
            weights: {
                [key: string]: number;
            };
        };
        /** Step */
        Step: {
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Ms */
            ms: number;
            /** Name */
            name: string;
            /** Status */
            status: string;
        };
        /** Sweep */
        Sweep: {
            /** Baseline Bond Lookback */
            baseline_bond_lookback: number;
            /** Baseline Risk On Rsi Window */
            baseline_risk_on_rsi_window: number;
            /** Bond Lookbacks */
            bond_lookbacks: number[];
            /** Cells */
            cells: components["schemas"]["SweepCell"][];
            /** Cost Bps */
            cost_bps: number;
            /** Risk On Rsi Windows */
            risk_on_rsi_windows: number[];
            /** Seconds */
            seconds: number;
        };
        /** SweepCell */
        SweepCell: {
            /** Bond Lookback */
            bond_lookback: number;
            periods: components["schemas"]["Periods"];
            /** Risk On Rsi Window */
            risk_on_rsi_window: number;
            /** Trades Per Year */
            trades_per_year: number;
        };
        /** System */
        System: {
            /** Built At */
            built_at: string;
            checks: components["schemas"]["Checks"] | null;
            /** Commit */
            commit: string | null;
            /** Data End */
            data_end: string;
            /** Data Source */
            data_source: string;
            /** Data Start */
            data_start: string;
            /** Endpoints */
            endpoints: components["schemas"]["Endpoint"][];
            /** Funds */
            funds: components["schemas"]["Fund"][];
            /** Output Hash */
            output_hash: string;
            /** Rows */
            rows: number;
            schedule: components["schemas"]["Schedule"];
        };
        /** TradeDay */
        TradeDay: {
            /** Date */
            date: string;
            /** Turnover */
            turnover: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    backtest_api_backtest_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backtest"];
                };
            };
        };
    };
    costs_api_costs_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Costs"];
                };
            };
        };
    };
    decisions_api_decisions__year__json_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["Decision"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_history_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["History"];
                };
            };
        };
    };
    run_list_api_runs_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    run_api_runs__day__json_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_status_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    sweep_api_sweep_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sweep"];
                };
            };
        };
    };
    system_api_system_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["System"];
                };
            };
        };
    };
}
